### ISSUE TITLE
Issues found in a real android device

### ISSUE THREAD

**Issue by pongponglau** [rauliyohmc/react-native-offline#25]
Thanks for the great offline library. When i run it in a real android. the following issues are found:

1) If i run the thunk actioncreator function in componentDidMount when there is no network (turn off wifi and 4G in the mobile phone), thunk return function will not be called when the network is resumed. 

2) There are occasions when the library cannot detect the network condition correctly.
a) when i enter into a lift of a high-rise building, network-off condition is detected correctly. However, when the real network is back after i come out from the lift, network-on condition is not detected.

b) bringing the app back from the background to the foreground, network-on condition is always not detected.

May i seek for your help?

Thank you very much.

**Comment by pongponglau** [comment]
I have solved the issues. The library is working great now in Android. I will try on iOS soon.

Cheers

**Comment by MrHubble** [comment]
@pongponglau are you able to share how you solved the issues?

**Comment by fredbt** [comment]
@pongponglau can you comment on how you solved some of your issues? I'm having similar problems on real devices as well (using redux integration and my root being wrapped by withNetworkConnectivity).

**Comment by fredbt** [comment]
Just for the record, I was having some issues with the real devices and it was apparently caused by a bad interaction with the <Root> component provided by native-base, which aws being used around my topmost container. My code was like:

```
let drc = withNetworkConnectivity({withRedux: true})(RootContainer)

class App extends Component {
  render () {
    return (
      <Provider store={store}>
        <Root>
           <drc />
       </Root>
      </Provider>
    )
  }
}
```
where <Root> was the native-base root container, required because of toasts, etc. I removed the dependency and it seems to be working now.

**Comment by yingdongzhang** [comment]
@fredbt 

In my case I do need the Toast from native-base, so I did a walkaround by passing the `isConnected` state to a `onFetch()` action creator, which will return `FETCH_OFFLINE_MODE` if `isConnected` is false, which stops the follow up actions from executing, otherwise it returns `FETCHING` to indicate the app is in fetching mode and continue executing.
