### ISSUE TITLE
Middleware doesn't work on Android / IOS for Preprod and Release BuiltType and real devices.

### ISSUE THREAD

**Issue by jchesne** [rauliyohmc/react-native-offline#26]
When i compile for developpement everything is workign fine, i am on airplane mode, start a fetch request and middleware catch it, perfect.

As soon as i switch to preprod or release config on Android and IOS, i do the exactly same test with same code, but unfortunately the middleware doesn't catch anything and i end up with this on Android Studio and XCode console : 

```
E/ReactNativeJS: [TypeError: Network request failed]
E/unknown:React: Network request failed, stack:
                                                  onerror@134:13650
                                                  value@124:1505
                                                 etc etc...
```

**Comment by pongponglau** [comment]
I can use the offline library successfully in iOS and Android in debug mode. However, when i run it in iOS release mode, the middleware part does not work, thus, it cannot intercept the thunk action call when there is no network. I have  no idea what is wrong now. 

May i ask if your problem is solved? If so, can you let me know how to solve it?

Thanks a lot

**Comment by rauliyohmc** [comment]
The problem is that the packager minifies the JS in production mode, in a way that function names are transformed and shortened, so the middleware doesn't understand that transformation. 

There is a simple workaround, which would be to add another property to the function returned by the thunk (apart from the optional meta), something like name. 

Would you like to put together a PR? :)

**Comment by jchesne** [comment]
It could be a pleasure to help you solving this issue, but i have strictly no idea how to do this :)

**Comment by pongponglau** [comment]
@rauliyohmc, i have tried your workaround "fetchData.interceptInOffline = true". However, the problem is still there with the release version. May i ask what else i can try?

Thank you.

**Comment by rauliyohmc** [comment]
I mean, that solution is not implemented yet, that's why I suggested you to create a PR :)

I'll try to release a new version over the weekend that fixes it.

**Comment by jchesne** [comment]
Fantastic, thank you Raul !

**Comment by pongponglau** [comment]
@Rauliyohmc,

I cannot get the thunk function properties in CreateNetworkMiddleware.js. It just return "undefined" when i call action.meta, and action.interceptInOffline.

The following is my thunk actioncreator function.

export function fetchHomeList(url) {
  let fetchData = (dispatch, getState) => {
      const {page, seed} = getState().myapp;
      return fetch(`${url}?seed=${seed}&page=${page}&results=20`)
          .then((response) => response.json())
          .then((res) => dispatch(setHomeList(res)))
          .catch((err) => dispatch(setHomeListError(err)));
      }
  }
  fetchData.meta = {
    retry: true, // By passing true, your thunk will be enqueued on offline mode
  };
  fetchData.interceptInOffline = true;
  return fetchData;
};

In the meantime, i am seeing how to create a pull request.

Thank you for your advice

**Comment by jay-at-avido** [comment]
Pardon my possibly limited knowledge of semantic versioning.. but how can this be on a 3.0 release version if it doesn't even work in production?
Sorry, just curious.

**Comment by rauliyohmc** [comment]
@jay-at-avido it is because I've been introducing breaking changes in the API, for the sake of improving it. It started as a bunch of utilities I wrapped up into a library, so I've been iterating a lot since then, stopping at each point of introducing a new feature and thinking about the best API I could offer to the consumer. Also, it's being my first OSS library shaped up, so as a beginner in that matter, I know the versioning it's a bit misleading, taking into account that the library has only 3 months since its creation.

I am using it in production and I can tell you it works perfectly with `redux-saga` and `redux-observable`. I hadn't tried out so far with `redux-thunk`. Even though the functionality is unit tested, I hadn't stumbled upon this issue in production (as you could see in the issue's thread). 

No offense taken ;) I encourage you to give it a try in your upcoming projects.

I'll try to put together between today and tomorrow. I know lots of people rely on `redux-thunk` as their middleware for side effects, so I am taking this as high priority.

**Comment by pongponglau** [comment]
@rauliyohmc, thank you so much for your great effort. Yes, you are right, plain action works properly in release mode, thus redux-saga and redux-observable would work perfectly.

Waiting for your new fix.

Thanks a lot.

**Comment by rauliyohmc** [comment]
@pongponglau I released a new minor version with the fix. Please let me know if it works now.

**Comment by pongponglau** [comment]
@rauliyohmc, sorry for my late reply.

I have tried your new release. It works great in ios release mode with thunk.

Nonetheless, the function property "meta = {retry: true,};" is also needed.

Thanks a lot.
