### ISSUE TITLE
How to intercept and queue other network states e.g. 401

### ISSUE THREAD

**Issue by sneerin** [rauliyohmc/react-native-offline#38]
Hi, It would be nice add to queue or retry after refreshing the key 401 failed results. maybe some other options. Can you suggest the best way to do so.

**Comment by rauliyohmc** [comment]
You can do that by dispatching yourself an action of type `@@network-connectivity/FETCH_OFFLINE_MODE`. The action types the library uses are exposed under `offlineActionTypes` property. Unfortunately, the action creators are not exposed yet, so I'll release soon a new version with that fixed. In the meantime, you can check that specific action creator in  [here](https://github.com/rauliyohmc/react-native-offline/blob/master/src/actionCreators.js#L18), so that you can emulate its payload.

```js
import { offlineActionTypes } from 'react-native-offline';
...
fetch('someurl/data').catch(error => {
  if (error.code === 401) {
    dispatch({
      type: actionTypes.FETCH_OFFLINE_MODE,
      payload: {
        prevAction: {
          type: action.type, // <-- action is the one that triggered your api call
          payload: action.payload,
        },
      },
      meta: { retry: true }
    })
  }
)


```

**Comment by rauliyohmc** [comment]
I added a FAQ section to the docs with this case: https://github.com/rauliyohmc/react-native-offline#how-to-intercept-and-queue-actions-when-the-server-responds-with-client-4xx-or-server-5xx-errors.

I am closing this for now. Let me know if you have further questions.

**Comment by raduflp** [comment]
exposing actionCreators will be useful as there are quite a few scenarios when one would want to enqueue manually certain actions. 
@rauliyohmc if you haven't started working on it, I can do a PR for this. 
Awesome lib btw
