### ISSUE TITLE
Question with regards to async action creators

### ISSUE THREAD

**Issue by greatwillow** [rauliyohmc/react-native-offline#48]
I am trying to understand something that is perhaps more related to redux code patterns but is highly relevant to my usage of this library.  Consider the situation where I am trying to fetch a users Id.  I would dispatch a function such

```
const fetchUserID = (userID) => {
  function thunk(dispatch) {
    const USER = { userID: userID };

    const USER_POST_URI =
      "https://someURL.com/users/create-user";

    fetch(USER_POST_URI, {
      headers: new Headers({
        Accept: "application/json",
        "Content-Type": "application/json"
      }),
      method: "POST",
      body: JSON.stringify(USER)
    })
      .then(res => {
        if (res.status == 200) {
          const XAUTH_TOKEN = res.headers.map["x-auth"][0];
          dispatch(actions.setUserToken(XAUTH_TOKEN));
          return res.json();
        } else {
          throw new Error("Something wrong with the server!");
        }
      })
      .then(data => {
        dispatch(actions.setUserID(data._id));
      })
      .catch(error => {
        console.error(error);
      });
  }
  thunk.interceptInOffline = true;
  return thunk;
};
```

Upon dispatching this action, if I was offline react-native-offline would place this action into an action queue to be retried later, and the following code (as taken from the docs in this repo) could be implemented to specify that the 'FETCH_USER_ID' action criteria for re-dispatching.

```
const fetchAction = {
  type: 'FETCH_USER_ID',
  payload: {
    id: 2
  },
  meta: {
    retry: true,
    dismiss: ['NAVIGATE_BACK']
  }
};
```

What I don't understand is how to link this 'FETCH_USER_ID' action type with my fetchUserID function.  If the 'fetchAction' above is dispatched, it specifies with type 'FETCH_USER_ID' in my reducers which piece of state to change, however, it is not recommended to dispatch an async action such as 'fetchUserID' from within the reducer, so how do I state that 'fetchUserID' is represented by the 'FETCH_USER_ID' action type to be dispatched.

Sorry if this is a bit confusing or verbose.  I sense that there is something pretty simple or fundamental that I'm missing here, though having a difficult time explaining it.  Any insight would be appreciated, and if there is any progress of a full example, this would be really useful.  Thanks!

**Comment by rauliyohmc** [comment]
As I can see on your code example, you are using `redux-thunk` as redux middleware.
That implies that, apart from plain objects, you are also dispatching functions, as it's the case when from your Component you call `dispatch(fetchUserID(userId))`. 

This is stated in this part of the docs: https://github.com/rauliyohmc/react-native-offline#thunks.

If you want the thunk (function), to be enqueued you need to provide `meta` property to the thunk as well, such as:

```js
thunk.meta = {
  retry: true,
};
```

Remember that functions are also objects in JS, so that's the way to instruct the middleware to enable queueing for your thunks.

When the connection is back online, the library will dispatch the thunk again, passing control to it and allowing to carry out the pertinent data fetching.

Hope that clarifies your question. Let me know otherwise.

**Comment by greatwillow** [comment]
Sorry, just getting back to this now.  Thanks! that works well now!  Looks like a missed that in the docs!
