### ISSUE TITLE
Can someone provide proper guide to redux integration. state.network is undefined. 

### ISSUE THREAD

**Issue by chetankotkar** [rauliyohmc/react-native-offline#58]
Here is my code for just getting isconnected  in redux state 

```
import { reducer as network } from 'react-native-offline';

const AppReducer = combineReducers({
  nav,
  maindata,
  network,
});

const sagaMiddleware = createSagaMiddleware();
const store = createStore(AppReducer,applyMiddleware(sagaMiddleware));
sagaMiddleware.run(rootSaga)
export default store;

```

I have tried with middleware nothing seems to work for me ..

Can you provide some working example ? with redux or with middleware like redux-saga.

**Comment by lexor90** [comment]
Hey there,

Not a maintainer nor a contributor to this library, but I want to help since at first, I had to spend some while to get it working:

 First off, did you see [this guide](https://github.com/rauliyohmc/react-native-offline#integration-with-redux)?

Specifically, you  have to make sure you follow all of the 3 steps to set up the integration properly:

1. export the reducer alongside your other reducers (using `combineReducers`)
2. in your "createStore" function make sure to add to your `applyMiddleware()` also `createNetworkMiddleware()` (it should be the first of your middlewares)
3. Wrap your main component using `withNetworkConnectivity({withRedux: true})`.

In your case I see you are missing the step n.2, you should revise your code to

    import { createNetworkMiddleware } from 'react-native-offline';
    // ...
    const networkMiddleware = createNetworkMiddleware();
    // ...
    const store = createStore(AppReducer,applyMiddleware(networkMiddleware, sagaMiddleware));


Remember to follow the step n.3 (and pass it the proper `withRedux: true` option).
I think it becomes harder to understand because of the wrong example in the README.md to the step number 1, but someone could easily PR it.

**Comment by sixertoy** [comment]
Hey!

I've done my integration with redux and react-navigation in this way:

```javascript
const ApplicationWithNetworkState = withNetworkConnectivity({
  // https://github.com/rauliyohmc/react-native-offline#config
  timeout: 5000,
  withRedux: true,
  withExtraHeadRequest: true,
  checkConnectionInterval: 0,
  pingServerUrl: 'https://google.com' // or any of your URLs
})(Application);

const AppWithNavigationState = connect(
  state => ({
    theme: state.theme,
    route: state.routes
  })
)(ApplicationWithNetworkState);

const store = configure();
const Root = () => (
  <Provider store={store}>
    <AppWithNavigationState />
  </Provider>
);
```

**Comment by rauliyohmc** [comment]
The steps are explained on this section: https://github.com/rauliyohmc/react-native-offline#network-reducer

@lexor90, step 2 is not strictly necessary if you just want the `network` subreducer on your redux state, but not the middleware.

@chetankotkar, if you are using `react-navigation` you'd have to wrap your top most component as already stated. If you are using another navigation library such as `react-native-navigation`, which implies several top most components (one per screen), make sure to wrap all your screens with `withNetworkConnectivity` and `withRedux: true` as configuration.
